title: "L-crown - 埼玉西武ライオンズデータサイト"
description: "西武ライオンズの成績・契約・ニュースをお届け #Lクラ"
theme: minima

# 記事URL
permalink: /news/:year/:month/:day/:title/

# 日本語対応
timezone: Asia/Tokyo
lang: ja

# GitHub Pages 公式サポートプラグインのみ
plugins:
  - jekyll-feed
